title: "Abdulrahman's Cybersecurity Portfolio"
description: "Showcasing projects and skills in Cybersecurity."
theme: minima
author: Abdulrahman (K4ZUM4KIRYU)

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact
